Document: pandorga-users-iniciais
Title: Debian pandorga-users-iniciais Manual
Author: <insert document author here>
Abstract: This manual describes what pandorga-users-iniciais is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/pandorga-users-iniciais/pandorga-users-iniciais.sgml.gz

Format: postscript
Files: /usr/share/doc/pandorga-users-iniciais/pandorga-users-iniciais.ps.gz

Format: text
Files: /usr/share/doc/pandorga-users-iniciais/pandorga-users-iniciais.text.gz

Format: HTML
Index: /usr/share/doc/pandorga-users-iniciais/html/index.html
Files: /usr/share/doc/pandorga-users-iniciais/html/*.html
